### ISSUE TITLE
Fails to load All / Tags / Performers containing more than 43 items

### ISSUE THREAD

**Issue by hmahler2** [gitgiggety/plugin.video.stash#1]
PythonToCppException thrown

Python callback ends with:

`".../resources/lib/listing/listing.py", line 87, in _create_item`
 `       'studio': scene ['studio']['name'],`
`    TypeError: 'NoneType' object is not subscriptable`

Perhaps some sort of handling for scenes with no studio.

**Comment by gitgiggety** [comment]
Thank you for the report :+1: My scenes always have a studio set so I didn't notice it was broken when no studio was set.
