### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by xboxguru** [gitgiggety/plugin.video.stash#6]
Increment playcount in stashapp when video is played.
Add ability to sort by list criteria like title, length, date, etc.

**Comment by gitgiggety** [comment]
> Increment playcount in stashapp when video is played.

Nice suggestion. But would require more (/lots of?) work. Also to respect the (Stash) configuration the user has set to track the play count etc. Furthermore the "Minimal play percentage" would make this hard(er) to implement as I think it can't be done as part of a video plugin (so either requires an additional plugin, or possible a single addon can implement multiple types, don't know).

> Add ability to sort by list criteria like title, length, date, etc.

This already works based on the saved filters (saved filters in Stash contain the order as well, when opening such a filter using this plugin it respects that sorting). To my knowledge it is not possible to implement custom sorting logic in a Kodi video plugin. So the only option for this would be to implement "folders" for all the sorting types. Which for me would be a disaster for the user experience and thus a "no".

**Comment by xboxguru** [comment]
Makes sense. Thanks for considering!
