### ISSUE TITLE
Fails to load with certain filters

### ISSUE THREAD

**Issue by xboxguru** [gitgiggety/plugin.video.stash#7]
Trying to load this Kodi plugin fails with an explanation to check the log for details.
The log has a python exception trace.  I don't have it currently handy.
This is reproducible by setting a filter in StashApp of "Stash ID" "is null" and saving it.

**Comment by gitgiggety** [comment]
Thanks for reporting. This was a general issue with filters without value, like "is null" / "is not null" etc. It should be fixed with 0.0.7 (just released).
